name: checkin-easy

on:
  schedule:
  - cron: "30 3 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        pip3 install -r ./checkin/core/easy/requirements.txt
    - name: Run
      run: |
        python3 ./checkin/job_easy.py "${{secrets.SOUTH_PLUS_COOKIE}}"
    - uses: gautamkrishnar/keepalive-workflow@v2
