name: nineone

on:
#  schedule:
#  - cron: "39 17 1/2 * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        pip3 install -r ./checkin/core/nineone/requirements.txt
    - name: Run
      run: |
        python3 ./checkin/job_91.py "${{secrets.MYSQL_HOST}}" "${{secrets.MYSQL_USER}}" "${{secrets.MYSQL_PWD}}" "${{secrets.MYSQL_PORT}}"
    - uses: gautamkrishnar/keepalive-workflow@v2
